DROP TABLE IF EXISTS users;
CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  location VARCHAR(100) NOT NULL
);

DROP TABLE IF EXISTS paintings;
CREATE TABLE paintings (
  id SERIAL PRIMARY KEY,
  item VARCHAR(100),
  price MONEY(16)
  user_id INTEGER REFERENCES users (id) NOT NULL
);